---
title: "Utilizando o Git e GitHub no RStudio"
#description: |
#  Uma lista de apresentações usando ou sobre R e Comunidades.
author:
  - name: Beatriz Milz 
    url: https://beatrizmilz.com
    affiliation: R-Ladies São Paulo
    affiliation_url: https://www.meetup.com/rladies-sao-paulo/
date: "Atualizado em `r Sys.Date()`"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Slides

<center>
<iframe src="https://beatrizmilz.github.io/slidesR/git_rstudio/index.html" height="100%" width="100%" style="min-height: 400px;"></iframe>
</center>

<p style="text-align:right;">[<i class="fas fa-external-link-alt"></i> Confira a apresentação](https://beatrizmilz.github.io/slidesR/git_rstudio/index.html)</p>

### Pré-requisitos

- [R](https://cran.r-project.org/)
- [RStudio](https://www.rstudio.com/products/rstudio/download/)
- [Git](https://git-scm.com/downloads)

- [Conta no GitHub](https://github.com/)


- Pacote `usethis`:

```{r echo=TRUE, eval=FALSE}
install.packages("usethis")
```


### Material Complementar

- Em breve!
  

### Meetups

Este material foi/será utilizado nos seguintes eventos/meetups:

- [R-Ladies Goiânia](https://www.sympla.com.br/git--rstudio__944832), 27 de agosto de 2020. [Acompanhe as perguntas no sli.do neste link](https://app.sli.do/event/zlvr87bu).

---

<center>
[<i class="fas fa-home"></i> Retorne à página inicial](index.html)
</center>